version: '3.3'

services:
  # Authentication Proxy - JWT validation layer
  auth-proxy:
    build: ./auth-proxy
    container_name: auth-proxy
    environment:
      - PORT=8081
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - JWT_PUBLIC_KEY_PATH=/app/public_key.pem
      - ALLOWED_ISSUERS=akto-auth,Akto
      - ALLOWED_AUDIENCES=
      - USE_ELASTICSEARCH=true
      - INSECURE_SKIP_VERIFY=false
    ports:
      - "8081:8081"
    depends_on:
      - elasticsearch
    restart: always

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    


